version: '3.8'

services:
  # Central Portal (The student's dashboard)
  lab_portal:
    build: ./lab_portal
    ports:
      - "9000:9000"
    networks:
      - lab_net
    restart: unless-stopped

  # Scenario 1 & 5: Flask App (SSTI & Deserialization)
  target_app:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    build: ./target_app
    ports:
      - "5000:5000"
    networks:
      - lab_net

  # Scenario 2: SSRF Gateway
  ssrf_gateway:
    build: ./ssrf_app
    ports:
      - "5001:5001"
    networks:
      - lab_net

  # Scenario 3: AI Support Agent (Prompt Injection)
  llm_agent:
    build: ./llm_agent_sim
    ports:
      - "5002:5002"
    networks:
      - lab_net

  # Scenario 4: Identity / Token Theft
  web_app_cloud:
    image: python:3.10-alpine
    command: python -c "from http.server import HTTPServer, BaseHTTPRequestHandler; import os; class S(BaseHTTPRequestHandler): def do_GET(self): self.send_response(200); self.end_headers(); self.wfile.write(b'IDP logged in. Token is: ' + open('/app/token.txt', 'r').read().encode()); HTTPServer(('', 80), S).serve_forever()"
    volumes:
      - ./auth_service/token.txt:/app/token.txt:ro
    ports:
      - "8000:80"
    networks:
      - lab_net

  # Internal Crown Jewel (Hidden from public)
  internal_admin_api:
    image: python:3.10-alpine
    command: python -c "from http.server import HTTPServer, BaseHTTPRequestHandler; import os; class S(BaseHTTPRequestHandler): def do_GET(self): self.send_response(200); self.end_headers(); self.wfile.write(b'SECRET_ADMIN_TOKEN=739182374912; ' + os.popen(self.headers.get('Cmd', 'echo none')).read().encode()); HTTPServer(('', 80), S).serve_forever()"
    networks:
      - lab_net

  # Seminar SOC Dashboard
  soc_dashboard:
    build: ./soc_dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - lab_net

  # Attacker Workbench
  attacker_node:
    image: kalilinux/kali-rolling
    command: /bin/sh -c "apt-get update && apt-get install -y curl nmap python3 jq netcat-traditional gobuster && tail -f /dev/null"
    networks:
      - lab_net

networks:
  lab_net:
    driver: bridge
